# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/appodeal/CocoaPods.git'

target 'iosdemo' do
    pod 'Appodeal', '~> 0.4.2’

end

